### ISSUE TITLE
Fix clock hands rotation

### ISSUE THREAD

**Issue by Theobano** [Tijani-zainab/Clock#1]
# Description
Currently, the clock hand rotation in the clock UI is not correct. The hands animate backwards on every full rotation. Unless this is a feature, it doesn't look so great.

To fix this issue, we should update the code that animates the rotation of the clock hands. This should ensure that the hands move smoothly.

# Steps to reproduce

Open the clock UI.
Observe the rotation of the clock hands.
Expected outcome:

The clock hands should rotate smoothly without animating bacwards.

# Actual outcome

The clock hands animate backwards on every full rotation, as if it is being reset.

**Comment by Tijani-zainab** [comment]
Thank you boss for the issue and for fixing it !
Nice Work ! @Theobano
